[package]
name = "rust-too-many-lists"
version = "0.1.0"
authors = ["prophet1996 <ishank.web.dev@gmailc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
